version: "3"

services:
  etherminer:
    container_name: etherminer
    build: ./
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command: ethminer -U -P stratum://${WALLET_ADDR}.${WORKER}@eu1.ethermine.org:14444
